# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/e6031b75-7626-4bf9-7079-40f5b7212650/volume/rsync-recipes/certifi-2020.4.5.1-python_3.7-on-osx, last modified Mon Apr  6 13:36:11 2020
# ------------------------------------------------

package:
    name: certifi
    version: 2020.4.5.1
source:
    -   folder: certifi
        sha256: 51fcb31174be6e6664c5f69e3e1691a2d72a1a12e90f872cbdb1567eb47b6519
        url: https://pypi.io/packages/source/c/certifi/certifi-2020.4.5.1.tar.gz
    -   folder: pip_wheel
        sha256: 993134f0475471b91452ca029d4390dc8f298ac63a712814f101cd1b6db46676
        url: https://pypi.io/packages/py2.py3/p/pip/pip-19.1.1-py2.py3-none-any.whl
    -   folder: setuptools_wheel
        sha256: c7769ce668c7a333d84e17fe8b524b1c45e7ee9f7908ad0a73e1eda7e6a5aebf
        url: https://pypi.io/packages/py2.py3/s/setuptools/setuptools-41.0.1-py2.py3-none-any.whl
build:
    number: '0'
    string: py37_0
requirements:
    host:
        - ca-certificates 2020.1.1 0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.2 h0a44026_0
        - openssl 1.1.1f h1de35cc_0
        - python 3.7.7 hc70fcce_0_cpython
        - readline 8.0 h1de35cc_0
        - sqlite 3.31.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - certifi
about:
    description: 'Certifi is a curated collection of Root Certificates for validating
        the

        trustworthiness of SSL certificates while verifying the identity of TLS

        hosts.

        '
    dev_url: https://github.com/certifi/python-certifi
    doc_source_url: https://github.com/certifi/certifi.io/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/certifi
    home: http://certifi.io/
    license: ISC
    license_file: certifi/LICENSE
    summary: Python package for providing Mozilla's CA Bundle.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - ocefpaf
        - pelson
        - sigmavirus24
