# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /Users/distiller/project/recipes/perl-xml-parser, last modified Sat May  4 06:25:16 2019
# ------------------------------------------------

package:
    name: perl-xml-parser
    version: '2.44'
source:
    sha256: 1ae9d07ee9c35326b3d9aad56eae71a6730a73a116b9fe9e8a4758b7cc033216
    url: https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.44.tar.gz
build:
    number: '7'
    string: pl526h776b7f1_7
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_16
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - expat 2.2.5 h0a44026_1002
        - libcxx 8.0.0 2
        - libcxxabi 8.0.0 2
        - perl 5.26.2 haec8ef5_1006
        - perl-extutils-makemaker 7.36 pl526_1
    run:
        - expat >=2.2.5,<2.3.0a0
        - perl >=5.26.2,<5.26.3.0a0
test:
    imports:
        - XML::Parser
        - XML::Parser::Expat
        - XML::Parser::Style::Debug
        - XML::Parser::Style::Objects
        - XML::Parser::Style::Stream
        - XML::Parser::Style::Subs
        - XML::Parser::Style::Tree
about:
    home: http://metacpan.org/pod/XML::Parser
    license: perl_5
    summary: A perl module for parsing XML documents
extra:
    copy_test_source_files: true
    final: true
