# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /opt/recipe, last modified Tue May 21 11:01:33 2019
# ------------------------------------------------

package:
    name: perl-net-http
    version: '6.19'
source:
    sha256: 52b76ec13959522cae64d965f15da3d99dcb445eddd85d2ce4e4f4df385b2fc4
    url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/Net-HTTP-6.19.tar.gz
build:
    noarch: true
    number: '0'
    string: pl526_0
requirements:
    host:
        - ca-certificates 2019.3.9 hecc5488_0
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - openssl 1.1.1b h14c3975_1
        - perl 5.26.2 h516909a_1006
        - perl-base 2.23 pl526_1
        - perl-business-isbn 3.004 pl526_0
        - perl-business-isbn-data 20140910.003 pl526_0
        - perl-carp 1.38 pl526_3
        - perl-compress-raw-zlib 2.086 pl526h6bb024c_1
        - perl-constant 1.33 pl526_1
        - perl-data-dumper 2.173 pl526_0
        - perl-encode 2.88 pl526_1
        - perl-exporter 5.72 pl526_1
        - perl-extutils-makemaker 7.36 pl526_1
        - perl-io-socket-ssl 2.066 pl526_0
        - perl-mime-base64 3.15 pl526_1
        - perl-net-ssleay 1.88 pl526h90d6eec_0
        - perl-parent 0.236 pl526_1
        - perl-socket 2.027 pl526_1
        - perl-uri 1.76 pl526_0
        - perl-xsloader 0.24 pl526_0
        - zlib 1.2.11 h14c3975_1004
    run:
        - perl >=5.26.2,<5.26.3.0a0
        - perl-base
        - perl-carp
        - perl-compress-raw-zlib
        - perl-io-socket-ssl
        - perl-uri
test:
    imports:
        - Net::HTTP
        - Net::HTTP::Methods
        - Net::HTTP::NB
        - Net::HTTPS
about:
    home: https://github.com/libwww-perl/Net-HTTP
    license: perl_5
    summary: Low-level HTTP connection (client)
extra:
    copy_test_source_files: true
    final: true
