# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/f50d9fd0-4410-47c0-6aa9-752924ac5fb2/volume/rsync-recipes/setuptools-45.2.0-python_3.7-on-osx, last modified Mon Feb 10 10:11:10 2020
# ------------------------------------------------

package:
    name: setuptools
    version: 45.2.0
source:
    patches:
        - 0001-Remove-exact-pinning-on-certifi-and-wincertstore.patch
        - 0002-disable-downloads-inside-conda-build.patch
    sha256: 1cee9d515859e83a409056189bb9f512881bf0fb3334609beed0cf8d384948fc
    url: https://github.com/pypa/setuptools/archive/v45.2.0.tar.gz
build:
    entry_points:
        - easy_install = setuptools.command.easy_install:main
    number: '0'
    string: py37_0
requirements:
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - python 3.7.6 h359304d_2
        - readline 7.0 h1de35cc_5
        - sqlite 3.31.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - certifi >=2016.9.26
        - python >=3.7,<3.8.0a0
test:
    commands:
        - easy_install --help
    imports:
        - easy_install
        - pkg_resources
        - setuptools
about:
    description: 'Setuptools is a fully-featured, actively-maintained, and stable
        library

        designed to facilitate packaging Python projects.

        '
    dev_url: https://github.com/pypa/setuptools
    doc_source_url: https://github.com/pypa/setuptools/tree/master/docs
    doc_url: http://pythonhosted.org/setuptools/
    home: https://github.com/pypa/setuptools
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Download, build, install, upgrade, and uninstall Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - nicoddemus
        - ocefpaf
