# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /Users/distiller/project/recipes/perl-base/2.23, last modified Sun Jul  8 05:29:16 2018
# ------------------------------------------------

package:
    name: perl-base
    version: '2.23'
source:
    sha256: 40f55841299a9fe6fab03cd098f94e9221fb516978e9ef40fd8ff2cbd6625dde
    url: https://cpan.metacpan.org/authors/id/R/RJ/RJBS/base-2.23.tar.gz
build:
    number: '1'
    string: pl526_1
requirements:
    build:
        - perl 5.26.2 h16c6ff1_0
        - perl-extutils-makemaker 7.34 pl526_0
    run:
        - perl >=5.26.2,<5.27.0a0
test:
    commands:
        - perl -e "use base"
about:
    home: http://metacpan.org/pod/base
    license: unknown
    summary: compile-time class fields
extra:
    copy_test_source_files: true
    final: true
