# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /Users/distiller/project/recipes/perl-file-listing, last modified Sat Jul  7 08:22:48 2018
# ------------------------------------------------

package:
    name: perl-file-listing
    version: '6.04'
source:
    md5: 83f636b477741f3a014585bb9cc079a6
    url: http://cpan.metacpan.org/authors/id/G/GA/GAAS/File-Listing-6.04.tar.gz
build:
    number: '1'
    string: pl526_1
requirements:
    host:
        - perl 5.26.2 h16c6ff1_0
        - perl-http-date 6.02 pl526_2
    run:
        - perl >=5.26.2,<5.27.0a0
        - perl-http-date
test:
    imports:
        - File::Listing
about:
    home: http://metacpan.org/pod/File-Listing
    license: perl_5
    summary: parse directory listing
extra:
    copy_test_source_files: true
    final: true
