# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /Users/distiller/project/recipes/perl-file-temp/0.2304, last modified Mon Jul  9 06:26:38 2018
# ------------------------------------------------

package:
    name: perl-file-temp
    version: '0.2304'
source:
    sha256: 13415323e48f7c9f34efdedf3d35141a7c3435e2beb8c6b922229dc317d321ac
    url: https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/File-Temp-0.2304.tar.gz
build:
    number: '2'
    string: pl526_2
requirements:
    host:
        - libgcc 4.8.5 hdbeacc1_10
        - libgfortran 3.0.1 h93005f0_2
        - perl 5.26.2 h16c6ff1_0
        - perl-app-cpanminus 1.7039 2
        - perl-carp 1.38 pl526_1
        - perl-constant 1.33 pl526_1
        - perl-devel-symdump 2.18 pl526_1
        - perl-exporter 5.72 pl526_1
        - perl-extutils-makemaker 7.34 pl526_0
        - perl-file-path 2.12 pl526_1
        - perl-parent 0.236 pl526_1
        - perl-threaded 5.22.0 10
    run:
        - perl >=5.26.2,<5.27.0a0
        - perl-app-cpanminus
        - perl-carp
        - perl-constant
        - perl-exporter
        - perl-file-path
        - perl-parent
test:
    imports:
        - File::Temp
about:
    home: https://github.com/Perl-Toolchain-Gang/File-Temp
    license: perl_5
    summary: return name and handle of a temporary file safely
extra:
    copy_test_source_files: true
    final: true
