# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /Users/distiller/project/recipes/perl-archive-tar, last modified Sun Nov 11 13:13:35 2018
# ------------------------------------------------

package:
    name: perl-archive-tar
    version: '2.32'
source:
    sha256: 92783780731ab0c9247adf43e70f4801e8317e3915ea87e38b85c8f734e8fca2
    url: http://search.cpan.org/CPAN/authors/id/B/BI/BINGOS/Archive-Tar-2.32.tar.gz
build:
    number: '0'
    string: pl526_0
requirements:
    host:
        - perl 5.26.2 h16c6ff1_0
        - perl-app-cpanminus 1.7044 pl526_1
        - perl-carp 1.38 pl526_1
        - perl-compress-raw-bzip2 2.074 pl526hfc679d8_0
        - perl-compress-raw-zlib 2.081 pl526h2d50403_0
        - perl-constant 1.33 pl526_1
        - perl-cpan-meta 2.120921 pl526_1
        - perl-data-dumper 2.161 pl526_2
        - perl-encode 2.88 pl526_1
        - perl-exporter 5.72 pl526_1
        - perl-extutils-cbuilder 0.280230 pl526_1
        - perl-extutils-makemaker 7.34 pl526_2
        - perl-extutils-manifest 1.70 pl526_2
        - perl-extutils-parsexs 3.35 pl526_0
        - perl-file-path 2.15 pl526_0
        - perl-file-temp 0.2304 pl526_2
        - perl-getopt-long 2.50 pl526_1
        - perl-io-compress 2.069 pl526hfc679d8_5
        - perl-io-zlib 1.10 pl526_2
        - perl-ipc-cmd 1.02 pl526_0
        - perl-locale-maketext-simple 0.21 pl526_1
        - perl-module-build 0.4224 pl526_3
        - perl-module-corelist 5.20180820 pl526_0
        - perl-module-load 0.32 pl526_1
        - perl-module-load-conditional 0.68 pl526_2
        - perl-module-metadata 1.000033 pl526_0
        - perl-params-check 0.38 pl526_1
        - perl-parent 0.236 pl526_1
        - perl-pathtools 3.73 pl526h470a237_2
        - perl-perl-ostype 1.010 pl526_1
        - perl-scalar-list-utils 1.45 pl526h470a237_3
        - perl-storable 3.11 pl526_0
        - perl-test-harness 3.42 pl526_0
        - perl-test-more 1.001002 pl526_1
        - perl-test-simple 1.302140 pl526_0
        - perl-text-abbrev 1.02 pl526_0
        - perl-text-parsewords 3.29 pl526_3
        - perl-version 0.9924 pl526_0
        - perl-xsloader 0.24 pl526_0
    run:
        - perl >=5.26.2,<5.26.3.0a0
        - perl-io-compress
        - perl-io-zlib
        - perl-pathtools
test:
    imports:
        - Archive::Tar
        - Archive::Tar::Constant
        - Archive::Tar::File
about:
    home: http://metacpan.org/pod/Archive::Tar
    license: perl_5
    summary: Manipulates TAR archives
extra:
    copy_test_source_files: true
    final: true
