# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /Users/distiller/project/recipes/perl-mime-base64, last modified Sun Jul  8 05:29:16 2018
# ------------------------------------------------

package:
    name: perl-mime-base64
    version: '3.15'
source:
    sha256: 7f863566a6a9cb93eda93beadb77d9aa04b9304d769cea3bb921b9a91b3a1eb9
    url: https://cpan.metacpan.org/authors/id/G/GA/GAAS/MIME-Base64-3.15.tar.gz
build:
    number: '1'
    string: pl526_1
requirements:
    host:
        - perl 5.26.2 h16c6ff1_0
        - perl-extutils-makemaker 7.34 pl526_0
        - perl-test-more 1.001002 pl526_1
        - perl-xsloader 0.22 pl526_1
    run:
        - perl >=5.26.2,<5.27.0a0
        - perl-xsloader
test:
    imports:
        - MIME::Base64
about:
    home: http://metacpan.org/pod/MIME::Base64
    license: perl_5
    summary: The RFC 2045 encodings; base64 and quoted-printable
extra:
    copy_test_source_files: true
    final: true
