# This file created by conda-build 3.10.6
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/b133cba7-a5c8-4924-7b0b-1252abc8cd61/volume/rsync-recipes/perl-5.26.2-on-osx, last modified Fri Jun  1 00:46:20 2018
# ------------------------------------------------

package:
    name: perl
    version: 5.26.2
source:
    sha256: 572f9cea625d6062f8a63b5cee9d3ee840800a001d2bb201a41b9a177ab7f70d
    url: http://www.cpan.org/src/5.0/perl-5.26.2.tar.gz
build:
    number: '0'
    string: h4e221da_0
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
        - make 4.2.1 h3efe00b_1
test:
    commands:
        - perl --help
about:
    description: 'Perl 5 is a highly capable, feature-rich programming language with
        over 29

        years of development. Perl 5 runs on over 100 platforms from portables to

        mainframes and is suitable for both rapid prototyping and large scale

        development projects.

        '
    dev_url: https://perl5.git.perl.org/perl.git
    doc_url: https://www.perl.org/docs.html
    home: http://www.perl.org/
    license: Perl Artistic
    license_family: Other
    summary: The Perl programming language interpreter.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - msarahan
