# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /Users/distiller/project/recipes/perl-encode/2.88, last modified Sun Jul  8 05:29:16 2018
# ------------------------------------------------

package:
    name: perl-encode
    version: '2.88'
source:
    sha256: e45ce444dfc87b01a16d3029d9a027beab1fdeff9860699b4b62a141420be338
    url: https://cpan.metacpan.org/authors/id/D/DA/DANKOGAI/Encode-2.88.tar.gz
build:
    number: '1'
    string: pl526_1
requirements:
    build:
        - perl 5.26.2 h16c6ff1_0
        - perl-exporter 5.72 pl526_1
        - perl-extutils-makemaker 7.34 pl526_0
        - perl-parent 0.236 pl526_1
    run:
        - perl >=5.26.2,<5.27.0a0
        - perl-exporter
        - perl-parent
test:
    commands:
        - perl -e "use Encode"
about:
    home: http://metacpan.org/pod/Encode
    license: perl_5
    summary: allows you to write your script in non-ASCII and non-UTF-8
extra:
    copy_test_source_files: true
    final: true
