# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /Users/distiller/project/recipes/entrez-direct, last modified Sun Feb  2 23:44:52 2020
# ------------------------------------------------

package:
    name: entrez-direct
    version: '13.3'
source:
    patches:
        - xtract.patch
    sha256: 63f06c4ef87bb8f61f38d5b729f6eaee5a98143a0dd58a3c8037a04de7b97f24
    url: ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/versions/13.3.20200128/edirect.tar.gz
build:
    number: '0'
    string: pl526h375a9b1_0
requirements:
    build:
        - go-nocgo 1.13.5 h8b2e17f_0
        - go-nocgo_osx-64 1.13.5 he44337e_0
    host:
        - ca-certificates 2019.11.28 hecc5488_0
        - expat 2.2.9 h4a8c4bd_2
        - libcxx 9.0.1 1
        - openssl 1.1.1d h0b31af3_0
        - perl 5.26.2 haec8ef5_1006
        - perl-app-cpanminus 1.7044 pl526_1
        - perl-base 2.23 pl526_1
        - perl-business-isbn 3.004 pl526_0
        - perl-business-isbn-data 20140910.003 pl526_0
        - perl-carp 1.38 pl526_3
        - perl-compress-raw-zlib 2.087 pl526h770b8ee_0
        - perl-constant 1.33 pl526_1
        - perl-data-dumper 2.173 pl526_0
        - perl-digest-hmac 1.03 pl526_3
        - perl-digest-md5 2.55 pl526_0
        - perl-encode 2.88 pl526_1
        - perl-encode-locale 1.05 pl526_6
        - perl-exporter 5.72 pl526_1
        - perl-extutils-makemaker 7.36 pl526_1
        - perl-file-listing 6.04 pl526_1
        - perl-file-path 2.16 pl526_0
        - perl-file-temp 0.2304 pl526_2
        - perl-html-parser 3.72 pl526h04f5b5a_5
        - perl-html-tagset 3.20 pl526_3
        - perl-html-tree 5.07 pl526_1
        - perl-http-cookies 6.04 pl526_0
        - perl-http-daemon 6.01 pl526_1
        - perl-http-date 6.02 pl526_3
        - perl-http-message 6.18 pl526_0
        - perl-http-negotiate 6.01 pl526_3
        - perl-io-html 1.001 pl526_2
        - perl-io-socket-ssl 2.066 pl526_0
        - perl-libwww-perl 6.39 pl526_0
        - perl-lwp-mediatypes 6.04 pl526_0
        - perl-lwp-protocol-https 6.07 pl526_4
        - perl-mime-base64 3.15 pl526_1
        - perl-mozilla-ca 20180117 pl526_1
        - perl-net-http 6.19 pl526_0
        - perl-net-ssleay 1.88 pl526hb1dc21d_0
        - perl-ntlm 1.09 pl526_4
        - perl-parent 0.236 pl526_1
        - perl-socket 2.027 pl526_1
        - perl-storable 3.15 pl526h1de35cc_0
        - perl-test-requiresinternet 0.05 pl526_0
        - perl-time-local 1.28 pl526_1
        - perl-try-tiny 0.30 pl526_1
        - perl-uri 1.76 pl526_0
        - perl-www-robotrules 6.02 pl526_3
        - perl-xml-namespacesupport 1.12 pl526_0
        - perl-xml-parser 2.44_01 pl526h4c9d1cc_1002
        - perl-xml-sax 1.02 pl526_0
        - perl-xml-sax-base 1.09 pl526_0
        - perl-xml-sax-expat 0.51 pl526_3
        - perl-xml-simple 2.25 pl526_1
        - perl-xsloader 0.24 pl526_0
        - zlib 1.2.11 h0b31af3_1006
    run:
        - perl >=5.26.2,<5.26.3.0a0
        - perl-html-parser
        - perl-html-tagset
        - perl-html-tree
        - perl-http-cookies
        - perl-http-date
        - perl-http-message
        - perl-http-negotiate
        - perl-io-socket-ssl
        - perl-lwp-mediatypes
        - perl-lwp-protocol-https
        - perl-mozilla-ca
        - perl-net-http
        - perl-uri
        - perl-www-robotrules
        - perl-xml-simple
test:
    commands:
        - efetch --help
        - epost --help
        - efilter --help
        - eproxy --help
        - einfo --help
        - esearch --help
        - econtact --help
        - elink --help
        - espell --help
        - enotify --help
        - esummary --help
        - entrez-phrase-search --help
        - xtract -version
about:
    home: ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/versions/13.3.20200128/README
    license: PUBLIC DOMAIN
    summary: Entrez Direct (EDirect) is an advanced method for accessing the NCBI's
        set of interconnected databases (publication, sequence, structure, gene, variation,
        expression, etc.) from a UNIX terminal window. Functions take search terms
        from command-line arguments. Individual operations are combined to build multi-step
        queries. Record retrieval and formatting normally complete the process.
extra:
    copy_test_source_files: true
    final: true
