# This file created by conda-build 3.17.7
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/a190565e-b538-439d-4b46-2627b8a1a06b/volume/rsync-recipes/libedit-3.1.20181209-on-osx, last modified Sat Jan 19 13:44:06 2019
# ------------------------------------------------

package:
    name: libedit
    version: 3.1.20181209
source:
    fn: libedit-20181209-3.1.tar.gz
    patches:
        - 0001-Also-look-in-libtinfo-for-tgetent.patch
    sha256: 2811d70c0b000f2ca91b7cb1a37203134441743c4fcc9c37b0b687f328611064
    url: http://thrysoee.dk/editline/libedit-20181209-3.1.tar.gz
build:
    number: '0'
    run_exports:
        - libedit >=3.1.20181209,<3.2.0a0
    string: hb402a30_0
requirements:
    build:
        - autoconf 2.69 pl526he370928_5
        - automake 1.16.1 pl526_0
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
        - m4 1.4.18 h1de35cc_1
        - make 4.2.1 h3efe00b_1
        - perl 5.26.2 h4e221da_0
    host:
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - ncurses 6.1 h0a44026_1
    run:
        - ncurses >=6.1,<7.0a0
test:
    commands:
        - test -f $PREFIX/lib/libedit.dylib
    downstreams:
        - sqlite
about:
    description: 'This is an autotool- and libtoolized port of the NetBSD Editline
        library

        (libedit). This Berkeley-style licensed command line editor library provides

        generic line editing, history, and tokenization functions, similar to those

        found in GNU Readline

        '
    home: http://thrysoee.dk/editline/
    license: NetBSD
    license_family: BSD
    license_file: COPYING
    summary: Editline Library (libedit)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dougalsutherland
        - mingwandroid
        - scopatz
