# This file created by conda-build 3.18.7
# meta.yaml template originally from:
# /Users/distiller/project/recipes/perl-io-compress, last modified Sat Aug 10 13:27:24 2019
# ------------------------------------------------

package:
    name: perl-io-compress
    version: '2.087'
source:
    sha256: 94f792775d0496fffe862363c76637e74ff5b46c40cf47042547686d164e23cb
    url: https://cpan.metacpan.org/authors/id/P/PM/PMQS/IO-Compress-2.087.tar.gz
build:
    number: '0'
    string: pl526h6de7cb9_0
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_17
        - clangxx 4.0.1 hc9b4283_0
        - clangxx_osx-64 4.0.1 h22b1bf0_17
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - libcxx 8.0.0 4
        - libcxxabi 8.0.0 4
        - perl 5.26.2 haec8ef5_1006
        - perl-compress-raw-bzip2 2.087 pl526h6de7cb9_0
        - perl-compress-raw-zlib 2.087 pl526h770b8ee_0
        - perl-extutils-makemaker 7.36 pl526_1
        - perl-scalar-list-utils 1.51 pl526h01d97ff_0
    run:
        - libcxx >=4.0.1
        - perl >=5.26.2,<5.26.3.0a0
        - perl-compress-raw-bzip2 >=2.087
        - perl-compress-raw-zlib >=2.087
        - perl-scalar-list-utils
test:
    imports:
        - IO::Compress::Adapter::Bzip2
        - IO::Compress::Adapter::Deflate
        - IO::Compress::Adapter::Identity
        - IO::Compress::Base
        - IO::Compress::Base::Common
        - IO::Compress::Bzip2
        - IO::Compress::Deflate
        - IO::Compress::Gzip
        - IO::Compress::Gzip::Constants
        - IO::Compress::RawDeflate
        - IO::Compress::Zip
        - IO::Compress::Zip::Constants
        - IO::Compress::Zlib::Constants
        - IO::Compress::Zlib::Extra
        - IO::Uncompress::Adapter::Bunzip2
        - IO::Uncompress::Adapter::Identity
        - IO::Uncompress::Adapter::Inflate
        - IO::Uncompress::AnyInflate
        - IO::Uncompress::AnyUncompress
        - IO::Uncompress::Base
        - IO::Uncompress::Bunzip2
        - IO::Uncompress::Gunzip
        - IO::Uncompress::Inflate
        - IO::Uncompress::RawInflate
        - IO::Uncompress::Unzip
about:
    home: http://metacpan.org/pod/IO-Compress
    license: perl_5
    summary: IO Interface to compressed data files/buffers
extra:
    copy_test_source_files: true
    final: true
