# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /Users/distiller/project/recipes/perl-io-zlib, last modified Mon Jul 16 16:51:36 2018
# ------------------------------------------------

package:
    name: perl-io-zlib
    version: '1.10'
source:
    sha256: fda584f55531e5102c350b9490673be3465e356602bf3b3d2a93f3a597f2d4d4
    url: https://cpan.metacpan.org/authors/id/T/TO/TOMHUGHES/IO-Zlib-1.10.tar.gz
build:
    number: '2'
    string: pl526_2
requirements:
    build:
        - perl 5.26.2 h16c6ff1_0
    run:
        - perl >=5.26.2,<5.27.0a0
test:
    imports:
        - IO::Zlib
about:
    home: http://metacpan.org/pod/IO::Zlib
    license: unknown
    summary: 'IO:: style interface to Compress::Zlib'
extra:
    copy_test_source_files: true
    final: true
