# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /Users/distiller/project/recipes/perl-xml-sax-base, last modified Mon Jul  9 22:13:25 2018
# ------------------------------------------------

package:
    name: perl-xml-sax-base
    version: '1.09'
source:
    sha256: 66cb355ba4ef47c10ca738bd35999723644386ac853abbeb5132841f5e8a2ad0
    url: https://cpan.metacpan.org/authors/id/G/GR/GRANTM/XML-SAX-Base-1.09.tar.gz
build:
    number: '0'
    string: pl526_0
requirements:
    host:
        - perl 5.26.2 h16c6ff1_0
        - perl-extutils-makemaker 7.34 pl526_0
    run:
        - perl >=5.26.2,<5.27.0a0
test:
    imports:
        - XML::SAX::Base
about:
    home: http://metacpan.org/pod/XML-SAX-Base
    license: perl_5
    summary: Base class for SAX Drivers and Filters
extra:
    copy_test_source_files: true
    final: true
