# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /Users/distiller/project/recipes/perl-pathtools, last modified Wed May  1 12:02:53 2019
# ------------------------------------------------

package:
    name: perl-pathtools
    version: '3.75'
source:
    sha256: a558503aa6b1f8c727c0073339081a77888606aa701ada1ad62dd9d8c3f945a2
    url: https://cpan.metacpan.org/authors/id/X/XS/XSAWYERX/PathTools-3.75.tar.gz
build:
    number: '1'
    string: pl526h1de35cc_1
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_16
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - perl 5.26.2 haec8ef5_1006
        - perl-carp 1.38 pl526_2
        - perl-exporter 5.72 pl526_1
        - perl-extutils-makemaker 7.36 pl526_0
    run:
        - perl >=5.26.2,<5.26.3.0a0
        - perl-carp
test:
    imports:
        - File::Spec::Functions
about:
    home: http://dev.perl.org/
    license: perl_5
    summary: Tools for working with directory and file names
extra:
    copy_test_source_files: true
    final: true
