# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /Users/distiller/project/recipes/blast, last modified Thu Sep 26 23:23:43 2019
# ------------------------------------------------

package:
    name: blast
    version: 2.9.0
source:
    sha256: a390cc2d7a09422759fc178db84de9def822cbe485916bbb2ec0d215dacdc257
    url: https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.9.0/ncbi-blast-2.9.0+-src.tar.gz
build:
    number: '4'
    string: pl526hb2f8ae4_4
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_17
        - clangxx 4.0.1 hc9b4283_0
        - clangxx_osx-64 4.0.1 h22b1bf0_17
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - bzip2 1.0.8 h01d97ff_1
        - ca-certificates 2019.9.11 hecc5488_0
        - curl 7.64.1 h22ea746_0
        - entrez-direct 11.0 pl526_0
        - expat 2.2.5 h6de7cb9_1003
        - krb5 1.16.3 hcfa6398_1001
        - libcurl 7.64.1 h16faf7d_0
        - libcxx 9.0.0 0
        - libcxxabi 9.0.0 0
        - libedit 3.1.20170329 hcfe32e1_1001
        - libssh2 1.8.2 hcdc9a53_2
        - ncurses 6.1 h0a44026_1002
        - openssl 1.1.1c h01d97ff_0
        - pcre 8.41 h0a44026_1003
        - perl 5.26.2 haec8ef5_1006
        - perl-base 2.23 pl526_1
        - perl-business-isbn 3.004 pl526_0
        - perl-business-isbn-data 20140910.003 pl526_0
        - perl-carp 1.38 pl526_3
        - perl-compress-raw-zlib 2.087 pl526h770b8ee_0
        - perl-constant 1.33 pl526_1
        - perl-data-dumper 2.173 pl526_0
        - perl-digest-hmac 1.03 pl526_3
        - perl-digest-md5 2.55 pl526_0
        - perl-encode 2.88 pl526_1
        - perl-encode-locale 1.05 pl526_6
        - perl-exporter 5.72 pl526_1
        - perl-extutils-makemaker 7.36 pl526_1
        - perl-file-listing 6.04 pl526_1
        - perl-html-parser 3.72 pl526h04f5b5a_5
        - perl-html-tagset 3.20 pl526_3
        - perl-html-tree 5.07 pl526_1
        - perl-http-cookies 6.04 pl526_0
        - perl-http-daemon 6.01 pl526_1
        - perl-http-date 6.02 pl526_3
        - perl-http-message 6.18 pl526_0
        - perl-http-negotiate 6.01 pl526_3
        - perl-io-html 1.001 pl526_2
        - perl-io-socket-ssl 2.066 pl526_0
        - perl-libwww-perl 6.39 pl526_0
        - perl-lwp-mediatypes 6.04 pl526_0
        - perl-lwp-protocol-https 6.07 pl526_4
        - perl-mime-base64 3.15 pl526_1
        - perl-mozilla-ca 20180117 pl526_1
        - perl-net-http 6.19 pl526_0
        - perl-net-ssleay 1.88 pl526hb1dc21d_0
        - perl-ntlm 1.09 pl526_4
        - perl-parent 0.236 pl526_1
        - perl-socket 2.027 pl526_1
        - perl-storable 3.15 pl526h1de35cc_0
        - perl-test-requiresinternet 0.05 pl526_0
        - perl-time-local 1.28 pl526_1
        - perl-try-tiny 0.30 pl526_1
        - perl-uri 1.76 pl526_0
        - perl-www-robotrules 6.02 pl526_3
        - perl-xml-namespacesupport 1.12 pl526_0
        - perl-xml-parser 2.44_01 pl526h4c9d1cc_1002
        - perl-xml-sax 0.99 pl526_1
        - perl-xml-sax-base 1.09 pl526_0
        - perl-xml-sax-expat 0.51 pl526_3
        - perl-xml-simple 2.25 pl526_1
        - perl-xsloader 0.24 pl526_0
        - tk 8.6.9 h2573ce8_1003
        - zlib 1.2.11 h01d97ff_1006
    run:
        - bzip2 >=1.0.8,<2.0a0
        - bzip2 >=1.0.8,<2.0a0
        - curl >=7.64.1,<8.0a0
        - entrez-direct
        - libcxx >=4.0.1
        - pcre >=8.41,<9.0a0
        - perl >=5.26.2,<5.26.3.0a0
        - perl-archive-tar
        - perl-json
        - perl-list-moreutils
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - blastn -help
        - blastp -help
        - makeblastdb -help
        - blastdb_aliastool -version > /dev/null
        - blastdbcheck -version > /dev/null
        - blastdbcmd -version > /dev/null
        - blastn -version > /dev/null
        - blastp -version > /dev/null
        - blastx -version > /dev/null
        - convert2blastmask -version > /dev/null
        - dustmasker -version > /dev/null
        - makeblastdb -version > /dev/null
        - makembindex -version > /dev/null
        - psiblast -version > /dev/null
        - rpsblast -version > /dev/null
        - rpstblastn -version > /dev/null
        - segmasker -version > /dev/null
        - tblastn -version > /dev/null
        - tblastx -version > /dev/null
        - windowmasker -version > /dev/null
        - update_blastdb.pl --version > /dev/null
        - get_species_taxids.sh -h > /dev/null
    files:
        - test.fa
        - testdatabase.fa
about:
    home: http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastDocs
    license: Public Domain
    summary: BLAST+ is a new suite of BLAST tools that utilizes the NCBI C++ Toolkit.
extra:
    copy_test_source_files: true
    final: true
    identifiers:
        - biotools:blast
        - doi:10.1016/S0022-2836(05)80360-2
    recipe-maintainers:
        - christiam
        - epruesse
