# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /Users/distiller/project/recipes/cap3, last modified Sun Jul  1 07:42:45 2018
# ------------------------------------------------

package:
    name: cap3
    version: '10.2011'
source:
    sha256: 4b6e8fa6b39147b23ada6add080854ea9fadace9a9c8870a97ac79ff1c75338e
    url: http://seq.cs.iastate.edu/CAP3/cap3.macosx.intel64.tar
build:
    number: '1'
    string: '1'
test:
    commands:
        - cap3 2>&1 | grep "12/21/07"
about:
    authors: Xiaoqiu Huang and Anup Madan
    home: http://seq.cs.iastate.edu/
    license: Michigan Tech.
    summary: DNA sequence assembly program.
extra:
    copy_test_source_files: true
    final: true
