# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/19bf69ef-5f0b-4ce3-6b3b-a9b70859c8c6/volume/rsync-recipes/conda-4.8.2-python_3.7-on-osx, last modified Fri Jan 24 12:54:53 2020
# ------------------------------------------------

package:
    name: conda
    version: 4.8.2
source:
    fn: conda-4.8.2.tar.gz
    sha256: 971d2e896a69bd4b4fb46f7f621bd573308a68489f54345e707b8dc8b2fd5be1
    url: https://github.com/conda/conda/archive/4.8.2.tar.gz
build:
    always_include_files:
        - bin/activate
        - bin/conda
        - bin/deactivate
    number: '0'
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py37_0
        - conda-package-handling 1.6.0 py37h1de35cc_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - pip 19.3.1 py37_0
        - python 3.7.6 h359304d_2
        - readline 7.0 h1de35cc_5
        - ruamel_yaml 0.15.87 py37h1de35cc_0
        - setuptools 44.0.0 py37_0
        - six 1.13.0 py37_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - tqdm 4.41.1 py_0
        - wheel 0.33.6 py37_0
        - xz 5.2.4 h1de35cc_4
        - yaml 0.1.7 hc338f04_2
        - zlib 1.2.11 h1de35cc_3
    run:
        - conda-package-handling >=1.3.0
        - pycosat >=0.6.3
        - pyopenssl >=16.2.0
        - python >=3.7,<3.8.0a0
        - requests >=2.18.4,<3
        - ruamel_yaml >=0.11.14,<0.16
        - setuptools >=31.0.1
    run_constrained:
        - conda-build >=3
        - conda-env >=2.6
        - cytoolz >=0.8.1
test:
    downstreams:
        - conda-smithy
    files:
        - test_conda.sh
    imports:
        - conda
        - conda_env
    requires:
        - mock
        - pexpect
        - pytest
        - responses
    source_files:
        - conftest.py
        - setup.cfg
        - tests
about:
    description: 'Conda is an open source package management system and environment
        management system for installing multiple versions of software packages and
        their dependencies and switching easily between them. It works on Linux, OS
        X and Windows, and was created for Python programs but can package and distribute
        any software.

        '
    dev_url: https://github.com/conda/conda
    doc_url: https://conda.io/projects/conda/en/latest/
    home: https://conda.io
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: OS-agnostic, system-level binary package and environment manager.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - kalefranz
        - mbargull
        - mcg1969
        - mingwandroid
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
