# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /Users/distiller/project/recipes/perl-json-xs/2.34, last modified Tue May  7 04:00:34 2019
# ------------------------------------------------

package:
    name: perl-json-xs
    version: '2.34'
source:
    sha256: a62fdf2777b9ae206aef382dbb62c9a126ce2ceef0229edacee3f6a9c78900ea
    url: https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/JSON-XS-2.34.tar.gz
build:
    number: '3'
    string: pl526h04f5b5a_3
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_16
        - clangxx 4.0.1 hc9b4283_0
        - clangxx_osx-64 4.0.1 h22b1bf0_16
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - libcxx 8.0.0 2
        - libcxxabi 8.0.0 2
        - perl 5.26.2 haec8ef5_1006
        - perl-canary-stability 2013 pl526_0
        - perl-common-sense 3.74 pl526_2
        - perl-extutils-makemaker 7.36 pl526_1
        - perl-types-serialiser 1.0 pl526_2
    run:
        - libcxx >=4.0.1
        - perl >=5.26.2,<5.26.3.0a0
        - perl-common-sense
        - perl-types-serialiser
test:
    imports:
        - JSON::XS
about:
    home: http://metacpan.org/pod/JSON::XS
    license: unknown
    summary: JSON serialising/deserialising, done correctly and fast
extra:
    copy_test_source_files: true
    final: true
