# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# /Users/distiller/project/recipes/perl-http-date, last modified Mon Aug 27 02:25:35 2018
# ------------------------------------------------

package:
    name: perl-http-date
    version: '6.02'
source:
    sha256: e8b9941da0f9f0c9c01068401a5e81341f0e3707d1c754f8e11f42a7e629e333
    url: https://cpan.metacpan.org/authors/id/G/GA/GAAS/HTTP-Date-6.02.tar.gz
build:
    number: '3'
    string: pl526_3
requirements:
    host:
        - perl 5.26.2 h16c6ff1_0
        - perl-carp 1.38 pl526_1
        - perl-constant 1.33 pl526_1
        - perl-data-dumper 2.161 pl526_2
        - perl-encode 2.88 pl526_1
        - perl-exporter 5.72 pl526_1
        - perl-extutils-makemaker 7.34 pl526_2
        - perl-parent 0.236 pl526_1
        - perl-time-local 1.28 pl526_1
    run:
        - perl >=5.26.2,<5.26.3.0a0
        - perl-time-local
test:
    imports:
        - HTTP::Date
about:
    home: http://metacpan.org/pod/HTTP::Date
    license: perl_5
    summary: date conversion routines
extra:
    copy_test_source_files: true
    final: true
