# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /Users/distiller/project/recipes/perl-http-negotiate, last modified Wed Mar 13 15:22:11 2019
# ------------------------------------------------

package:
    name: perl-http-negotiate
    version: '6.01'
source:
    sha256: 1c729c1ea63100e878405cda7d66f9adfd3ed4f1d6cacaca0ee9152df728e016
    url: https://cpan.metacpan.org/authors/id/G/GA/GAAS/HTTP-Negotiate-6.01.tar.gz
build:
    number: '3'
    string: pl526_3
requirements:
    host:
        - libcxx 7.0.0 h2d50403_1
        - llvm-meta 7.0.0 0
        - perl 5.26.2 h79c3c89_1002
        - perl-base 2.23 pl526_1
        - perl-business-isbn 3.004 pl526_0
        - perl-business-isbn-data 20140910.003 pl526_0
        - perl-carp 1.38 pl526_2
        - perl-compress-raw-zlib 2.084 pl526h04f5b5a_1
        - perl-constant 1.33 pl526_1
        - perl-data-dumper 2.173 pl526_0
        - perl-encode 2.88 pl526_1
        - perl-encode-locale 1.05 pl526_6
        - perl-exporter 5.72 pl526_1
        - perl-extutils-makemaker 7.34 pl526_3
        - perl-http-date 6.02 pl526_3
        - perl-http-message 6.18 pl526_0
        - perl-io-html 1.001 pl526_2
        - perl-lwp-mediatypes 6.02 pl526_3
        - perl-mime-base64 3.15 pl526_1
        - perl-parent 0.236 pl526_1
        - perl-storable 3.11 pl526_0
        - perl-time-local 1.28 pl526_1
        - perl-uri 1.76 pl526_0
        - perl-xsloader 0.24 pl526_0
    run:
        - perl >=5.26.2,<5.26.3.0a0
        - perl-http-message
test:
    imports:
        - HTTP::Negotiate
about:
    home: http://metacpan.org/pod/HTTP::Negotiate
    license: perl_5
    summary: choose a variant to serve
extra:
    copy_test_source_files: true
    final: true
