# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /Users/distiller/project/recipes/perl-types-serialiser, last modified Tue Jul 31 14:42:30 2018
# ------------------------------------------------

package:
    name: perl-types-serialiser
    version: '1.0'
source:
    sha256: 7ad3347849d8a3da6470135018d6af5fd8e58b4057cd568c3813695f2a04730d
    url: https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/Types-Serialiser-1.0.tar.gz
build:
    number: '2'
    string: pl526_2
requirements:
    host:
        - perl 5.26.2 h16c6ff1_0
        - perl-common-sense 3.74 pl526_2
        - perl-extutils-makemaker 7.34 pl526_0
    run:
        - perl >=5.26.2,<5.26.3.0a0
        - perl-common-sense
test:
    imports:
        - Types::Serialiser
        - Types::Serialiser::Error
about:
    home: http://metacpan.org/pod/Types::Serialiser
    license: perl_5
    summary: Simple data types for common serialisation formats
extra:
    copy_test_source_files: true
    final: true
