# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# /Users/distiller/project/recipes/perl-html-tagset, last modified Thu Aug 23 20:03:35 2018
# ------------------------------------------------

package:
    name: perl-html-tagset
    version: '3.20'
source:
    sha256: adb17dac9e36cd011f5243881c9739417fd102fce760f8de4e9be4c7131108e2
    url: https://cpan.metacpan.org/authors/id/P/PE/PETDANCE/HTML-Tagset-3.20.tar.gz
build:
    number: '3'
    string: pl526_3
requirements:
    host:
        - perl 5.26.2 h16c6ff1_0
    run:
        - perl >=5.26.2,<5.26.3.0a0
test:
    imports:
        - HTML::Tagset
about:
    home: http://metacpan.org/pod/HTML::Tagset
    license: unknown
    summary: data tables useful in parsing HTML
extra:
    copy_test_source_files: true
    final: true
