# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /Users/distiller/project/recipes/perl-app-cpanminus, last modified Tue Jul 17 11:42:10 2018
# ------------------------------------------------

package:
    name: perl-app-cpanminus
    version: '1.7044'
source:
    sha256: 9b60767fe40752ef7a9d3f13f19060a63389a5c23acc3e9827e19b75500f81f3
    url: https://cpan.metacpan.org/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7044.tar.gz
build:
    number: '1'
    string: pl526_1
requirements:
    host:
        - perl 5.26.2 h16c6ff1_0
        - perl-extutils-makemaker 7.34 pl526_0
    run:
        - perl >=5.26.2,<5.27.0a0
test:
    imports:
        - App::cpanminus
about:
    home: https://github.com/miyagawa/cpanminus
    license: perl_5
    summary: get, unpack, build and install modules from CPAN
extra:
    copy_test_source_files: true
    final: true
