# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/b42446ab-12db-450c-4b31-18208943956f/volume/rsync-recipes/krb5-1.17.1-on-osx, last modified Mon Dec 16 17:01:26 2019
# ------------------------------------------------

package:
    name: krb5
    version: 1.17.1
source:
    sha256: 8bdedbfb0bbb245217e23290437916d70b315514e6f7cc088b6e82d1310afe0b
    url: https://github.com/krb5/krb5/archive/krb5-1.17.1-final.tar.gz
build:
    missing_dso_whitelist:
        - /usr/lib/libresolv.9.dylib
    number: '0'
    run_exports:
        - krb5 >=1.17.1,<1.18.0a0
    string: hddcf347_0
requirements:
    build:
        - autoconf 2.69 pl526he370928_5
        - bison 3.4 h0a44026_1
        - ca-certificates 2019.11.27 0
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - clangxx 4.0.1 1
        - clangxx_osx-64 4.0.1 h22b1bf0_18
        - compiler-rt 4.0.1 hcfea43d_1
        - flex 2.6.4 hb56bbfa_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - libiconv 1.15 hdd342a3_7
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
        - m4 1.4.18 h1de35cc_1
        - make 4.2.1 h3efe00b_1
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - perl 5.26.2 h4e221da_0
        - pkg-config 0.29.2 h3efe00b_8
        - python 3.7.5 h359304d_0
        - readline 7.0 h1de35cc_5
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    host:
        - ca-certificates 2019.11.27 0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - tk 8.6.8 ha441bb4_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - libcxx >=4.0.1
        - libedit >=3.1.20181209,<3.2.0a0
        - libedit >=3.1.20181209,<4.0a0
        - openssl >=1.1.1d,<1.1.2a
        - tk >=8.6.8,<8.7.0a0
test:
    commands:
        - conda inspect linkages -p $PREFIX krb5
        - conda inspect objects -p $PREFIX krb5
    requires:
        - python 3.7.*
about:
    home: http://web.mit.edu/kerberos/
    license: MIT
    license_file: doc/notice.rst
    summary: A network authentication protocol.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mariusvniekerk
        - mingwandroid
        - ocefpaf
        - pelson
