# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /opt/recipe, last modified Tue Jun 18 21:40:42 2019
# ------------------------------------------------

package:
    name: perl-xml-sax
    version: '1.02'
source:
    sha256: 4506c387043aa6a77b455f00f57409f3720aa7e553495ab2535263b4ed1ea12a
    url: https://cpan.metacpan.org/authors/id/G/GR/GRANTM/XML-SAX-1.02.tar.gz
build:
    noarch: generic
    number: '0'
    string: pl526_0
requirements:
    host:
        - libgcc-ng 9.1.0 hdf63c60_0
        - perl 5.26.2 h516909a_1006
        - perl-app-cpanminus 1.7044 pl526_1
        - perl-carp 1.38 pl526_3
        - perl-constant 1.33 pl526_1
        - perl-exporter 5.72 pl526_1
        - perl-extutils-makemaker 7.36 pl526_1
        - perl-file-path 2.16 pl526_0
        - perl-file-temp 0.2304 pl526_2
        - perl-parent 0.236 pl526_1
        - perl-xml-namespacesupport 1.12 pl526_0
        - perl-xml-sax-base 1.09 pl526_0
    run:
        - perl >=5.26.2,<5.26.3.0a0
        - perl-file-temp
        - perl-xml-namespacesupport
        - perl-xml-sax-base
test:
    imports:
        - XML::SAX
        - XML::SAX::DocumentLocator
        - XML::SAX::PurePerl
        - XML::SAX::PurePerl::DebugHandler
        - XML::SAX::PurePerl::Exception
        - XML::SAX::PurePerl::Productions
        - XML::SAX::PurePerl::Reader
        - XML::SAX::PurePerl::Reader::Stream
        - XML::SAX::PurePerl::Reader::String
        - XML::SAX::PurePerl::Reader::URI
about:
    home: http://metacpan.org/pod/XML::SAX
    license: unknown
    summary: Simple API for XML
extra:
    copy_test_source_files: true
    final: true
