# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/e96323ce-2a5d-417e-7d68-64860287950c/volume/rsync-recipes/cryptography-2.8-python_3.7-on-osx, last modified Mon Oct 21 15:12:40 2019
# ------------------------------------------------

package:
    name: cryptography
    version: '2.8'
source:
    sha256: 3cda1f0ed8747339bbdf71b9f38ca74c7b592f24f65cdb3ab3765e4b02871651
    url: https://pypi.io/packages/source/c/cryptography/cryptography-2.8.tar.gz
build:
    number: '0'
    script:
        - python -m pip install --no-deps --ignore-installed . -vv
    string: py37ha12b0ac_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py37_0
        - cffi 1.12.3 py37hb5b8e2f_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - pip 19.3.1 py37_0
        - pycparser 2.19 py37_0
        - python 3.7.4 h359304d_1
        - readline 7.0 h1de35cc_5
        - setuptools 41.4.0 py37_0
        - sqlite 3.30.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.33.6 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - asn1crypto >=0.21.0
        - cffi >=1.8
        - idna >=2.1
        - openssl >=1.1.1d,<1.1.2a
        - python >=3.7,<3.8.0a0
        - six >=1.4.1
test:
    commands:
        - pytest
    imports:
        - cryptography
        - cryptography.fernet
        - cryptography.hazmat
        - cryptography.hazmat.backends
        - cryptography.hazmat.backends.openssl
        - cryptography.hazmat.bindings
        - cryptography.hazmat.bindings.openssl
        - cryptography.hazmat.primitives
        - cryptography.hazmat.primitives.asymmetric
        - cryptography.hazmat.primitives.ciphers
        - cryptography.hazmat.primitives.kdf
        - cryptography.hazmat.primitives.twofactor
        - cryptography.x509
        - cryptography.x509.certificate_transparency
    requires:
        - cryptography-vectors 2.8.*
        - hypothesis >=1.11.4
        - iso8601
        - pretend
        - pytest >=3.2.1,!=3.3.0
        - pytz
    source_files:
        - tests
about:
    description: 'Cryptography is a package which provides cryptographic recipes and

        primitives to Python developers. Our goal is for it to be your

        "cryptographic standard library". It supports Python 2.6-2.7, Python 3.3+,

        and PyPy 2.6+. Cryptography includes both high level recipes, and low level

        interfaces to common cryptographic algorithms such as symmetric ciphers,

        message digests and key derivation functions.

        '
    dev_url: https://github.com/pyca/cryptography
    doc_source_url: https://github.com/pyca/cryptography/tree/master/docs
    doc_url: http://cryptography.readthedocs.io/
    home: https://github.com/pyca/cryptography
    license: Apache 2.0 or BSD 3-Clause, PSF 2
    license_family: BSD
    license_file: LICENSE
    summary: Provides cryptographic recipes and primitives to Python developers
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jschueller
        - ocefpaf
