# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/a8318fc0-dc0a-4d44-51cf-4dc4160f283e/volume/rsync-recipes/conda-package-handling-1.6.0-python_3.7-on-osx, last modified Fri Sep 20 15:59:58 2019
# ------------------------------------------------

package:
    name: conda-package-handling
    version: 1.6.0
source:
    fn: conda-package-handling-1.6.0.tar.gz
    sha256: ab3389859be35be6113bc9ce57032fb5a287f699ca2c71ffa470cff6dfd1b542
    url: https://github.com/conda/conda-package-handling/releases/download/1.6.0/conda-package-handling-1.6.0.tar.gz
build:
    entry_points:
        - cph = conda_package_handling.cli:main
    number: '0'
    script: /opt/concourse/worker/volumes/live/a8318fc0-dc0a-4d44-51cf-4dc4160f283e/volume/conda-package-handling_1569013402583/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
        -m pip install . --no-deps -vv
    string: py37h1de35cc_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - _libarchive_static_for_cph 3.3.3 h190e6e7_0
        - ca-certificates 2019.5.15 1
        - certifi 2019.6.16 py37_1
        - cython 0.29.13 py37h0a44026_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_1
        - pip 19.2.2 py37_0
        - python 3.7.4 h359304d_1
        - readline 7.0 h1de35cc_5
        - setuptools 41.0.1 py37_0
        - sqlite 3.29.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.33.4 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.7,<3.8.0a0
        - six
        - tqdm
test:
    commands:
        - pytest tests
    imports:
        - conda_package_handling
        - conda_package_handling.archive_utils_cy
    requires:
        - mock
        - pytest
        - pytest-cov
        - pytest-mock
    source_files:
        - tests
about:
    home: https://github.com/conda/conda-package-handling
    license: BSD-3-Clause
    license_family: BSD
    license_file:
        - LICENSE
        - static_deps_licenses/bzip2.txt
        - static_deps_licenses/libarchive.txt
        - static_deps_licenses/libiconv.txt
        - static_deps_licenses/zlib.txt
        - static_deps_licenses/zstd.txt
    summary: Create and extract conda packages of various formats
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jjhelmus
        - msarahan
