# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /Users/distiller/project/recipes/samtools/1.3.1, last modified Tue Nov 12 06:36:21 2019
# ------------------------------------------------

package:
    name: samtools
    version: 1.3.1
source:
    md5: a7471aa5a1eb7fc9cc4c6491d73c2d88
    url: https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2
build:
    number: '6'
    string: h9a800e7_6
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_17
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - ca-certificates 2019.9.11 hecc5488_0
        - curl 7.64.1 h22ea746_0
        - krb5 1.16.3 hcfa6398_1001
        - libcurl 7.64.1 h16faf7d_0
        - libcxx 9.0.0 h89e68fa_1
        - libedit 3.1.20170329 hcfe32e1_1001
        - libssh2 1.8.2 hcdc9a53_2
        - ncurses 6.1 h0a44026_1002
        - openssl 1.1.1d h0b31af3_0
        - tk 8.6.9 h2573ce8_1003
        - zlib 1.2.11 h0b31af3_1006
    run:
        - curl >=7.64.1,<8.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - samtools --help
about:
    home: https://github.com/samtools/samtools
    license: MIT
    summary: Tools for dealing with SAM, BAM and CRAM files
extra:
    copy_test_source_files: true
    final: true
